apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: vault
    port: 8200
    targetPort: 8200
    protocol: TCP
  - name: cluster
    port: 8201
    targetPort: 8201
    protocol: TCP
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: infrastructure
