apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflare
type: Opaque
data:
  # Replace this with your actual Cloudflare tunnel token encoded in base64
  # To encode: echo -n "your-token-here" | base64
  token: "ZXlKaElqb2lOelpqWmpnellUUTRNelJoTnprd1l6TTRaVEE1TldNMk5XUmlaak0xWmpBaUxDSjBJam9pTjJVeVpqVXdORE10TkdJeVppMDBZV0V4TFdGbE56RXROVGt3TlRJNVpEZG1aams1SWl3aWN5STZJbHBFWXpCTmVrMTZUbXBWZEZwVVpHeE5VekF3V21wQmVVeFhTVEJPYWtsMFRqSkthRTU2VW1sYVZGWnFUbGRWTUNKOQ=="
