apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflare
type: Opaque
data:
  # Replace this with your actual Cloudflare tunnel token encoded in base64
  # To encode: echo -n "your-token-here" | base64
  token: "UkVQTEFDRV9XSVRIX1ZPVVJfQkFTRTY0X0VOQ09ERVJfVE9LRU4="
