apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/azhe403/argocd-learn.git
    targetRevision: HEAD
    path: argocd-manifests/apps/nodejs-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
  namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true