apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-app
  namespace: argocd-learn
spec:
  project: microservices
  source:
    repoURL: https://github.com/azhe403/argocd-learn.git
    targetRevision: HEAD
    path: argocd-manifests/apps/golang-app/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-learn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true