apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/azhe403/argocd-learn.git
    path: apps/nodejs
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
