apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-learn-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: argocd-learn-ca
  secretName: argocd-learn-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: argocd-learn-ca-issuer
spec:
  ca:
    secretName: argocd-learn-ca-secret
